const uint8_t layer2[KEYS] = {
	//ROW1			ROW2				ROW3			ROW4			ROW5
	KEY_TILDE,		KEY_TAB,			KEY_RIGHT_CTRL|KEY_MOD,KEY_ALT_TAB,KEY_ESC,				// COL1
	KEY_1,			KEY_QUOTE,			KEY_A,			KEY_GUI|KEY_MOD,KEY_LAYER1,				// COL2
	KEY_2,			KEY_COMMA,			KEY_O,			KEY_Q,			KEY_SEMICOLON,			// COL3
	KEY_3,			KEY_PERIOD,			KEY_E,			KEY_J,			KEY_LEFT_ALT|KEY_MOD,	// COL4
	KEY_4,			KEY_P,				KEY_U,			KEY_K,			KEY_LEFT_CTRL|KEY_MOD,	// COL5
	KEY_5,			KEY_Y,				KEY_I,			KEY_X,			KEY_MY_SHIFT,			// COL6
	KEY_6,			KEY_F,				KEY_D,			KEY_B,			KEY_SPACE,				// COL7 
	KEY_7,			KEY_G,				KEY_H,			KEY_M,			KEY_FN,					// COL8
	KEY_8,			KEY_C,				KEY_T,			KEY_W,			KEY_RIGHT_ALT|KEY_MOD,	// COL9
	KEY_9,			KEY_R,				KEY_N,			KEY_V,			KEY_Z,					// COL10
	KEY_0,			KEY_L,				KEY_S,			KEY_BACKSLASH,	KEY_LAYER2,				// COL11
	KEY_LEFT_BRACE,	KEY_SLASH,			KEY_MINUS,		KEY_EQUAL,		KEY_RIGHT_BRACE			// COL12

/*	KEY_ESC,			KEY_LAYER1,			KEY_RIGHT_CTRL|KEY_MOD,KEY_TAB,	KEY_TILDE,		// COL0
	KEY_ALT_TAB,		KEY_SEMICOLON,		KEY_A,			KEY_QUOTE,		KEY_1,			// COL1
	KEY_GUI|KEY_MOD,	KEY_Q,			KEY_O,			KEY_COMMA,		KEY_2,			// COL2
	KEY_ALT|KEY_MOD,	KEY_J,				KEY_E,			KEY_PERIOD,		KEY_3,			// COL3
	KEY_CTRL|KEY_MOD,	KEY_K,				KEY_U,			KEY_P,			KEY_4,			// COL4
	KEY_MY_SHIFT,		KEY_X,				KEY_I,			KEY_Y,			KEY_5,			// COL5
	KEY_SPACE,			KEY_B,				KEY_D,			KEY_F,			KEY_6,			// COL6 
	KEY_FN,				KEY_M,				KEY_H,			KEY_G,			KEY_7,			// COL7
	KEY_RIGHT_ALT|KEY_MOD,KEY_W,			KEY_T,			KEY_C,			KEY_8,			// COL8
	KEY_BACKSLASH,		KEY_V,				KEY_N,			KEY_R,			KEY_9,			// COL9
	KEY_EQUAL,			KEY_Z,				KEY_S,			KEY_L,			KEY_0,			// COL10
	KEY_RIGHT_BRACE,	KEY_LAYER2,			KEY_MINUS,		KEY_SLASH,		KEY_LEFT_BRACE	// COL11*/
};
