// Dvorak
const uint8_t layer2[KEYS] = {
	//ROW1			ROW2				ROW3			ROW4			ROW5
	KEY_TILDE,		KEY_TAB,			KEY_RCTRL,		KEY_ALT_TAB,	KEY_ESC,		// COL1
	KEY_1,			KEY_QUOTE,			KEY_A,			KEY_LGUI,		KEY_LAYER1,		// COL2
	KEY_2,			KEY_COMMA,			KEY_O,			KEY_Q,			KEY_SEMICOLON,	// COL3
	KEY_3,			KEY_PERIOD,			KEY_E,			KEY_J,			KEY_LALT,		// COL4
	KEY_4,			KEY_P,				KEY_U,			KEY_K,			KEY_LCTRL,		// COL5
	KEY_5,			KEY_Y,				KEY_I,			KEY_X,			KEY_MY_SHIFT,	// COL6
	KEY_6,			KEY_F,				KEY_D,			KEY_B,			KEY_SPACE,		// COL7 
	KEY_7,			KEY_G,				KEY_H,			KEY_M,			KEY_FN,			// COL8
	KEY_8,			KEY_C,				KEY_T,			KEY_W,			KEY_RALT,		// COL9
	KEY_9,			KEY_R,				KEY_N,			KEY_V,			KEY_Z,			// COL10
	KEY_0,			KEY_L,				KEY_S,			KEY_BACKSLASH,	KEY_LAYER2,		// COL11
	KEY_LEFT_BRACE,	KEY_SLASH,			KEY_MINUS,		KEY_EQUAL,		KEY_RIGHT_BRACE	// COL12
};
