// jcuken fywa
const uint8_t layer2[KEYS] = {
	//ROW1			ROW2				ROW3			ROW4			ROW5
	KEY_TILDE,		KEY_TAB,			KEY_RCTRL,		KEY_ALT_TAB,	KEY_ESC,		// COL1
	KEY_1,			KEY_J,				KEY_F,			KEY_LGUI,		KEY_LAYER1,		// COL2
	KEY_2,			KEY_C,				KEY_Y,			KEY_SLASH,		KEY_Q,			// COL3
	KEY_3,			KEY_U,				KEY_W,			KEY_S,			KEY_LALT,		// COL4
	KEY_4,			KEY_K,				KEY_A,			KEY_M,			KEY_LCTRL,		// COL5
	KEY_5,			KEY_E,				KEY_P,			KEY_I,			KEY_MY_SHIFT,	// COL6
	KEY_6,			KEY_N,				KEY_R,			KEY_T,			KEY_SPACE,		// COL7 
	KEY_7,			KEY_G,				KEY_O,			KEY_X,			KEY_FN,			// COL8
	KEY_8,			KEY_H,				KEY_L,			KEY_B,			KEY_RALT,		// COL9
	KEY_9,			KEY_V,				KEY_D,			KEY_COMMA,		KEY_PERIOD,		// COL10
	KEY_0,			KEY_Z,				KEY_SEMICOLON,	KEY_BACKSLASH,	KEY_LAYER2,		// COL11
	KEY_MINUS,		KEY_LEFT_BRACE,		KEY_QUOTE,		KEY_RIGHT_BRACE,KEY_EQUAL		// COL12
};
