// Моя немного модифицированная раскладка
const uint8_t layer2[KEYS] = {
	//ROW0				ROW1				ROW2			ROW3			ROW4
	KEY_ESC,			KEY_LAYER1,			KEY_RIGHT_CTRL|KEY_MOD,KEY_TAB,	KEY_TILDE,		// COL0
	KEY_ALT_TAB,		KEY_Q,				KEY_F,			KEY_J,			KEY_1,			// COL1
	KEY_GUI|KEY_MOD,	KEY_SLASH,			KEY_Y,			KEY_C,			KEY_2,			// COL2
	KEY_ALT|KEY_MOD,	KEY_S,				KEY_W,			KEY_U,			KEY_3,			// COL3
	KEY_CTRL|KEY_MOD,	KEY_M,				KEY_A,			KEY_K,			KEY_4,			// COL4
	KEY_MY_SHIFT,		KEY_I,				KEY_P,			KEY_E,			KEY_5,			// COL5
	KEY_SPACE,			KEY_T,				KEY_R,			KEY_N,			KEY_6,			// COL6 
	KEY_FN,				KEY_X,				KEY_O,			KEY_G,			KEY_7,			// COL7
	KEY_RIGHT_ALT|KEY_MOD,KEY_B,			KEY_L,			KEY_H,			KEY_8,			// COL8
	KEY_BACKSLASH,		KEY_COMMA,			KEY_D,			KEY_V,			KEY_9,			// COL9
	KEY_RIGHT_BRACE,	KEY_PERIOD,			KEY_SEMICOLON,	KEY_Z,			KEY_0,			// COL10
	KEY_EQUAL,			KEY_LAYER2,			KEY_QUOTE,		KEY_LEFT_BRACE,	KEY_MINUS		// COL11
};
